### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [mourinhan8/SplayTree#1]
1. Поля `left` и `right`в классе `SplayTree` выглядят странно: нужно ли вам результат `split` хранить в объекте класса? Может стоит возвращать их из `split` в виде пары?
2. Очень странный подход с балансировкой при чтении. Лучше это делать при добавлении/удалении. Сейчас, например, после `SplayTreeTest.add` дерево вырождено в линейный список.
3. `remove` в итераторе можно реализовать эффективнее, если запоминать в стеке путь до текущей вершины.
4. `add` и `remove` два раза ищут элемент: один раз в `contains` и второй раз непосредстенно при вставке. Это лучше исправить.
5. Непонятно, зачем проверка на `getClass` в `containsAll`, `addAll` и `retainAll`, `removeAll`,причём только для первого элемента.
6. Почитайте документацию по интерфейсу `Set`, в частности по методам `equals` и `hashCode`. `equals` должен уметь сравниваться с другими реализациями `Set`. `hashCode` должен вычисляться определённым образом.
7. `headSet`, `tailSet` и `subSet` должны возвращать отображения множества. То есть при удалении/добавлении элементов в исходном множестве, эти изменения должны отображаться и в этих отображениях и наоборот.
8. GUI не нашёл

**Comment by mourinhan8** [comment]
Здравствуйте!
Я исправил несколько пункт. Можно подсказать мне как исправить пункт 7. Эти методы были очень сложными задачам на упражнениях по теориям. И я не знаю какой способ, что делать по лучше.
Спасибо Вам.

**Comment by gagarski** [comment]
Проще всего сделать ещё одну реализацию `SortedSet` со следующими полями:

```java
class SplaySubSet<T> implements SortedSet<T> {
    private SplayTree<T> tree;
    private Integer lowerBound;  // null for headSet
    private Integer upperBound;  // null for tailSet

    // ...
}
```

При реализации почти всех методов `SplaySubSet` вам нужно проверить, попадаем ли мы в границы. Если нет, то вернуть нужное значение (в зависимости от метода), если да, то вызвать такой же метод на `tree`. Получится довольно много кода, но логика в основном простая и однообразная.

**Comment by gagarski** [comment]
1. При добавлении дерево всё ещё почему-то не балансируется (судя по вашей GUI-шной демонстрации). Попробуйте добавить: 1, 2, 3, 4, 5
2. Метод `Splay` следует назвать с маленькой буквы.
3. Дореализуйте методы в `SplaySubSet`.Там почти всё делается тривиально.

**Comment by mourinhan8** [comment]
Здравствуйте!
По пункту 1 я думаю когда добаление (1, 2, 3, 4, 5) то 5 будет splay на root. Я пробовал с этом приложением (https://www.cs.usfca.edu/~galles/visualization/SplayTree.html) и со своем GUI. Подскажите мне, пожалуйста.

**Comment by gagarski** [comment]
Да, ок, всё в порядке.

Но наткнулся на баг: добавляем 1, 2, 3, 4, 5, удаляем 3, потом 5, получается что-то не то.

**Comment by mourinhan8** [comment]
я исправил эту ошибку. Если вам удобно, можно пробовать еще раз?

**Comment by gagarski** [comment]
Остался итератор у `SubSet`
